[package]
name = "delta-sharing-core"
version = "0.1.0"
edition = "2021"
authors = ["Robert Pack <robstar.pack@gmail.com>"]

[dependencies]
# workspace dependencies
serde.workspace = true
async-trait.workspace = true
thiserror.workspace = true

# core dependencies
pbjson = { version = "0.6" }
prost = { version = "0.12" }

dashmap = { version = "5", optional = true }
object_store = { version = "0.9", optional = true }
uuid = { version = "1.8", optional = true, features = ["v5"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[features]
default = ["memory"]
memory = ["dashmap", "object_store", "uuid"]
