[package]
name = "testutils"
version = "1.0.0"
authors = ["Shingo OKAWA <shingo.okawa.g.h.c@gmail.com>"]
edition = "2021"
rust-version = "1.67"

[dependencies]
chrono = "0.4.23"
rand = "0.8.5"
regex = "1.4.2"
tempfile = "3.3.0"
uuid = { version = "1.3.0", features = [ "v4", "serde" ] }