version: "3.9"
services:
  app:
    image: kotosiro/sharing:latest
    restart: always
    environment:
      - AWS_SHARED_CREDENTIALS_FILE=/.aws/credentials
      - GOOGLE_APPLICATION_CREDENTIALS=/.gcp/service-account-file.json
      - KOTOSIRO_DB_URL=postgres://postgres:secret@db:5432/sharing
      - KOTOSIRO_SERVER_ADDR=http://127.0.0.1:8080
      - KOTOSIRO_SERVER_BIND=0.0.0.0:8080
      - KOTOSIRO_ADMIN_NAME=kotosiro
      - KOTOSIRO_ADMIN_EMAIL=kotosiro@email.com
      - KOTOSIRO_ADMIN_PASSWORD=password
      - KOTOSIRO_ADMIN_NAMESPACE=kotosiro
      - KOTOSIRO_ADMIN_TTL=28800
      - KOTOSIRO_SIGNED_URL_TTL=28800
      - KOTOSIRO_JWT_SECRET=secret
      - KOTOSIRO_AWS_PROFILE=kotosiro-sharing
      - KOTOSIRO_AWS_REGION=ap-northeast-1
      - KOTOSIRO_USE_JSON_LOG=true
      - KOTOSIRO_LOG_FILTER=warn,kotosiro_sharing=info
    ports:
      - 8080:8080
    volumes:
      - ~/.aws/credentials:/.aws/credentials
      - ~/.gcp/service-account-file.json:/.gcp/service-account-file.json
    command:
      server
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=sharing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
